//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSLL.MS.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vmemberingroup
    {
        public int ChurchMemberID { get; set; }
        public int GroupID { get; set; }
        public Nullable<System.DateTime> JointDate { get; set; }
        public string RolesID { get; set; }
        public string Roles { get; set; }
        public string GroupName { get; set; }
        public int GroupTypeID { get; set; }
        public string GroupType { get; set; }
    }
}
