//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSLL.MS.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vmember
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MembershipNo { get; set; }
        public string AbbrName { get; set; }
        public Nullable<System.DateTime> BOD { get; set; }
        public Nullable<System.DateTime> JointDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string EnglishName { get; set; }
    }
}
